services:

  carting-service:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - carting-db

  carting-db:
    image: mongodb/mongodb-community-server:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
