services:

  catalog-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8080:8081"
    depends_on:
      - catalog-db

  catalog-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=example1234
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"